### ISSUE TITLE
Inspecting existing stubs/expectations

### ISSUE THREAD

**Issue by jmnsf** [edgurgel/mimic#13]
I'm writing some generic code for my tests that calls Mimic's `allow/3` on `Task.async` when in the test environment, so that I can write async code without worrying whether it's going to be testable or not.

The problem is if no stubs or expectations were created for the Mock, the `allow/3` call raises since [there's no case for an empty list](https://github.com/edgurgel/mimic/blob/master/lib/mimic/server.ex#L269-L274). I'm working around this in my own code by calling `:ets` directly as if I were Mimic, but would prefer a less hacky solution.

I could do a PR for this, but there are multiple possible solutions, wondering what you think would be preferrable:

1. Adding an empty list case as a no-op in `allow`.
2. Adding an empty list case but returning an error/warning instead.
3. Exposing a function in the `Mimic` module for inspecting the existing stubs/expectations on a Mock.
4. _something else_?

Thanks!

Edit: it'd also be useful to access the currently active mode, since we can't `allow` when `:global`. I'm using `:sys.get_state(Mimic.Server)` atm as a workaround.

**Comment by edgurgel** [comment]
First, thanks for the opening this issue and explaining everything so well.

I think the most consistent response is to keep throwing ArgumentErrors when allow fails. So maybe  this one makes more sense:

> 2. Adding an empty list case but returning an error/warning instead.

> it'd also be useful to access the currently active mode, since we can't allow when :global. I'm using :sys.get_state(Mimic.Server) atm as a workaround.

Happy to have something like `Mimic.mode` that returns `:global` or `private` 

What do you think?

**Comment by jmnsf** [comment]
Sounds good! I'll put something together 👍

**Comment by jmnsf** [comment]
@edgurgel created a PR for the mode function here: https://github.com/edgurgel/mimic/pull/14

I was a bit hasty in replying before; raising an `ArgumentError` doesn't let me prevent an error with `allow`, which is mostly what I'm looking for. It's a better wrapper than a match error, but still an error :) 

Doesn't feel right to return `:ok` on a no-op though, and returning `{:warn, :no_stub}` or similar would be a major change to the API, so maybe it'd make sense to be able to either 1) check if a mock exists, or 2) return the current mocks?

```elixir
# 1)
iex> Mimic.mocked?(SomeModule)
true

iex> Mimic.mocked?(SomeModule, :some_fun, :some_arity)
false

# 2)
iex> Mimic.mocks()
[%{...}]
```

What do you think?

**Comment by edgurgel** [comment]
I wonder if we should do something like this https://github.com/dashbitco/mox/pull/53 ? Use the $callers data from the process dictionary ?

This solution will probably cover most issues?

**Comment by jmnsf** [comment]
@edgurgel definitely, would bypass the need for the allows in the first place :)

This goes a bit into uncharted elixir territory for me but I'll see if I can put something together 👍

**Comment by edgurgel** [comment]
No worries. I may give it a try this weekend to see how hard this will be to adapt Mimic's code. Thanks for starting this change :)
