### ISSUE TITLE
error copying erlang modules

### ISSUE THREAD

**Issue by sescobb27** [edgurgel/mimic#15]
when trying to copy erlang modules there is an error printed out and copying doesn't succeed, is this intended? how can i copy/mock these kind of modules? thanks

```
15:32:21.833 [error] Can't load module ':rpc' that resides in sticky dir

  1) test success registering with manager (Worker.RegisterTest)
     apps/worker/test/regiser_test.exs:7
     ** (ArgumentError) Module :rpc has not been copied.  See docs for Mimic.copy/1
     code: expect(:rpc, :call, fn args ->
     stacktrace:
       (mimic) lib/mimic.ex:423: Mimic.raise_if_not_copied!/1
       (mimic) lib/mimic.ex:200: Mimic.expect/4
       test/regiser_test.exs:9: (test)

```

**Comment by edgurgel** [comment]
Hey thanks for opening this issue. I'm not sure if we want to support copying standard library modules like `rpc`. I would suggest wrapping up the erlang module with your own module and mocking your own module.

**Comment by sescobb27** [comment]
yeah, that's what i end up doing, the problem was i was doing a refactor on a client code and as i didn't want to break anything i was adding tests first and was trying to mock `:rpc` but i end up moving those call to an external module in order to mock them. Maybe it would be nice to add some docs about it the same as meck https://github.com/eproxus/meck#caveats 

thanks for your response.

**Comment by edgurgel** [comment]
@sescobb27, yeah good point! I will add a note to the README :thumbsup:
