### ISSUE TITLE
UndefinedFunctionError while compiling on Elixir 1.9 with Erlang 22.

### ISSUE THREAD

**Issue by jimsynz** [edgurgel/mimic#21]
Hey Jerk.

I tried to add Mimic to a project which hasn't been reupped to the latest and greatest and got the following error at compile time:

```
** (UndefinedFunctionError) function :cover.compile_beams/1 is undefined or private. Did you mean one of:

      * compile/1
      * compile/2
      * compile_beam/1
      * compile_beam_directory/0
      * compile_beam_directory/1

    :cover.compile_beams([{Backbone.Charge.HookHandler.Mimic.Original.Module, <<70, 79, 82, 49, 0, 0, 36, 32, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 4, 48, 0, 0, 0, 65, 56, 69, 108, 105, 120, 105, 114, 46, 66, 97, 99, 107, 98, 111, 110, 101, 46, 67, 104, 97, 114, 103, 101, ...>>}])
    lib/mimic/module.ex:45: Mimic.Module.rename_module/2
    lib/mimic/module.ex:27: Mimic.Module.replace!/1
    lib/mimic.ex:343: Mimic.copy/1
    test/test_helper.exs:3: (file)
```

The output of `elixir --version`:
```
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.9.4 (compiled with Erlang/OTP 22)
```

I had to go all the way back to Mimic 1.0.0 to get it to work.

Thanks!

**Comment by edgurgel** [comment]
Hey! Yeah we depend on cover to be available: https://github.com/edgurgel/mimic/issues/8

**Comment by edgurgel** [comment]
I might add `:cover` here: https://github.com/edgurgel/mimic/blob/master/mix.exs#L23

**Comment by jimsynz** [comment]
Hey. Yeah, that's a start, but I also note that there's [no `compile_beams/1` in the Erlang `:cover` documentation](https://erlang.org/doc/man/cover.html).

**Comment by edgurgel** [comment]
Hah you got me: https://blog.gurgel.me/accessing-private-functions-in-elixir 🙈
