### ISSUE TITLE
Mimic is not using a stub function if that function is called by a function in the same module

### ISSUE THREAD

**Issue by azzahidK** [edgurgel/mimic#27]
Hello,
So recently i realize if you call a function that have a stub with a function in the same module that does not have stub. 
The second function is actually calling the original function of the stubbed function. 
Is there a way to overcome this limitation and make the second function to call the stub instead of the original function.

Thank you. 
PS: If it's not possible it's alright, I'll create a separate module that will be the one that i make as a module for stubbed function.

**Comment by jimsynz** [comment]
@azzahidK this has bit me too. The BEAM optimises calls to functions within a module, there are two ways to make it work:

1. Call the inner function as if calling it from the outside (ie `MyModule.inner_function()`), or
2. as you suggest, move it to another module.

**Comment by azzahidK** [comment]
Thank you @jimsynz for the suggestion i'll try the first solution that you offer.
