### ISSUE TITLE
simple api for verifying reject before another expect/stub

### ISSUE THREAD

**Issue by techgaun** [edgurgel/mimic#29]
Lets say, we've following module & test:

```elixir
defmodule Calculator do
  def calculate(:div, num1, num2) do
    divide(num1, num2)
  end

  def calculate(_, num1, num2) do
    // do other things
  end

  def divide(num1, 0), do: :error
  def divide(num1, num2), do: num1 / num2
end
```

```elixir
reject(&Calculator.divide/2)
Calculator.calculate(:add, 3, 4)

expect(Calculator, :divide, fn _, _ -> 42 end)
Calculator.calculate(:div, 100, 5)
```

Right now, it gives `Mimic.UnexpectedCallError` which makes sense. I wanted to assert no call was made on the first round but on second round, it does make call and the `expect` should work but `reject` needs to be invalidated at this point via some construct.

I tried doing:

```elixir
reject(&Calculator.divide/2)
Calculator.calculate(:add, 3, 4)

verify!()

expect(Calculator, :divide, fn _, _ -> 42 end)
Calculator.calculate(:div, 100, 5)
```

But it does not seem to work. Can we have a simple API to achieve this? Of course, in most cases, we can probably split the test into two cases but this is just a contrived example and sometimes for real world stuff, need that within a single test case.

**Comment by edgurgel** [comment]
I would need to test it myself but I think the issue here is that the call to divide is local so you would need to change the calculate code to use Calculator.divide instead of simply divide. Otherwise erlang treats it differently AFAIK. Again I'm not 100% sure but this would be my guess.

**Comment by techgaun** [comment]
@edgurgel sorry I've updated the example. I did have fully qualified calls in my actual tests. Let me re-try in case I missed something. Thanks!
