### ISSUE TITLE
Adding support for `stubs_with`

### ISSUE THREAD

**Issue by calvin-kargo** [edgurgel/mimic#30]
Hi @edgurgel , would adding support for `stubs_with` functionality, a function to completely mock a module with another module, is something that align with `Mimic`? 

`stubs_with` would have similar behaviour to [Mox](https://hexdocs.pm/mox/Mox.html#stub_with/2), which is:
1. it would completely redirect all of call to original module in test to stubbed module
2. It would take lowest precedence, so if there's a new stub / expect at test code, that will take higher precedence

short example that i can think of is like
```
defmodule RedisCache do
  def fetch_cache(key), do: ...
  def put_cache(key, value), do: ...
end
....
defmodule TestRedisCache do
  # SImple cache by process dictionary
  def get_cache(key), do: Process.get(key, :none_value)
  end
  def put_cache(key, value), do: Process.put(key, value)
end
....
#test_helper.ex
Mimic.stubs_with(RedisCache, TestRedisCache)
```

**Comment by edgurgel** [comment]
I wonder if `Mimic.stub/1` does what you want? https://hexdocs.pm/mimic/Mimic.html#stub/1

**Comment by edgurgel** [comment]
Hi @calvin-karg,

I think this would be a great addition to the library!

**Comment by calvin-kargo** [comment]
raised PR for implementing stubs_with/2, sorry it's so long due to me taking vacation
