### ISSUE TITLE
warning: this clause for __mimic_info__/0 cannot match because a previous clause at line 94 always matches

### ISSUE THREAD

**Issue by dylan-chong** [edgurgel/mimic#31]
```
    warning: this clause for __mimic_info__/0 cannot match because a previous clause at line 94 always matches
     .../_deps/mimic/lib/mimic/module.ex:94
```

This seems to be caused by `Mimic.copy(MyModule)` in `test/support/bla.ex`. `bla.ex`'s function gets called in the `setup` block of the test

**Comment by edgurgel** [comment]
So I think the issue here is that on every setup call it's copying the module. But the module should be copied once before tests start inside `test_helper.exs`. I think Mimic should raise an error if it's copied multiple times :thinking:
