### ISSUE TITLE
Faster/Optional Mimic.copy for TDD

### ISSUE THREAD

**Issue by calvin-kargo** [edgurgel/mimic#32]
Hi @edgurgel , 

Is it good to make Mimic.copy optional/faster so that starting `mix test` would be faster?

recently i was practicing TDD at a project at work which use Mimic a lot,  during that time, i realize that `Mimic.copy` is taking a long time, making the starting of test (`mix app.start test/some_test.exs`) become really slow. that project was having `Mimic.copy` ~100 module. and the reason `Mimic.copy` is slow is because one of the operation, `rename_module` is slow, it was decompiling & recompiling module to rename it. if the module size is big, then `rename_module` would take long time to finish.

currently i was hacking it to make sure when i was in TDD_MODE, test_helper.exs would disable most of `Mimic.copy`, with this i reduce test startup time from ~45 second to ~5 second.

I was considering on how to solve this problem in general, some ideas:
- make rename module faster, currently it's decompiling & recompiling, which is slow. quick google search find https://github.com/trapexit/erlang-hacks/blob/master/beam/src/beam_renamer.erl which able to rename it on OTP BEAM file byte level, but i am not sure if this work / how to proceed with it.
- enable on demand `Mimic.copy`, the idea is at test file, there's a function which would run `Mimic.copy` if a particular module isn't copied before (with unique single worker to make sure async test doesn't have problem), it looks somewhat like this
```elixir
#test_helper.exs
if not tdd_mode? do
  Mimic.copy(MockedModule)
  ...
end

#test/some_test.exs
defmodule SomeTest do
  setup do
    Mimic.ensure_copied!(MockedModule)
  end

  test "some test" do
    Mimic.stub(MockedModule ....)
    ...
  end
end
```  

Elixir version: 1.10.3, OTP 22, Mimic version 1.5.0

**Comment by calvin-kargo** [comment]
Here's how i was implementing on demand mimic on my project current setup
```elixir
  @doc """
    Ensure that Mimic has already copied a module for purposes of mocking
    This function is usually used in TDD_MODE=true, to enable on demand Mimic.copy (usually on setup)
    because copying all module at test startup is slow (~45 second)
    This function will check if Mimic has copied a module or not, then it will copy it if it hasn't
    This function is safe concurrently, it use ConCache to ensure only single worker will do copying at one time
  """
  def ensure_mimic_copied!(module) do
    ConCache.get_or_store(:generic_cache, {:ensure_mimic_copied!, module}, fn ->
      backup_module = Mimic.Module.original(module)
      backup_module_exist? = Code.ensure_compiled?(backup_module)

      if backup_module_exist? do
        :ok
      else
        Mimic.copy(module)
        :ok
      end

      %ConCache.Item{
        ttl: :timer.seconds(1),
        value: :ok
      }
    end)    
  end

#some_test.exs
setup do
  ensure_mimic_copied!(MockedModule)
end
```

**Comment by edgurgel** [comment]
Hi @calvin-kargo ! 

Thanks for the very detailed issue and for proposing solutions! 

I would love to keep the existing behaviour (using Mimic.copy) if possible but I wouldn't be surprised if it's impossible. Because of that I think it might be worth checking if this erlang hack works 🤔 .

I also wonder if firing Mimic.copy in parallel with something like [Task.async_stream](https://hexdocs.pm/elixir/1.12/Task.html#async_stream/3) would work?

So maybe like a `Mimic.copy([mod1, mod2, ...])` that would try to parallelise the copy step? Not sure which parts of the erlang code server would lock but it would be good to test it out?

If nothing of the above works I think the best approach is on-demand copying 👌 Which is good to know that it works for you already 🎉 .

**Comment by calvin-kargo** [comment]
Hi @edgurgel , thanks for replying!

>So maybe like a Mimic.copy([mod1, mod2, ...]) that would try to parallelise the copy step? Not sure which parts of the erlang code server would lock but it would be good to test it out?

actually just tested this, parallelizing Mimic.copy does reduce test startup time at my current project from 45 second to 26 second on my machine, but 26 second for startup is still too long for effective TDD cycle.

After trying out the parallelization, i am not sure if it's something that could be made into easy to use function/library, and the reason is because the option on parallelization, such as max_worker or timeout, is really dependent on the size of the project & machine used. If Mimic do expose such functionality, then it would need to considered how to adjust the parallelization parameter, which is a bit of stretch of how i usually use Mimic. Alternative to implementing `Mimic.copy([mod1, mod2, ...])` directly on `Mimic`, maybe it could just mention on how to speed it up on large project using `Task.async_stream`?

>If nothing of the above works I think the best approach is on-demand copying ok_hand Which is good to know that it works for you already tada .

yes, it work really nicely, it reduce the test time for specific file test from 45 to 6 second
