### ISSUE TITLE
Retrieving call count to easily make assertions on call count

### ISSUE THREAD

**Issue by Ziinc** [edgurgel/mimic#49]
currently, the `expect/3` api only performs call assertion at the end of the test case. However, there are situations where it is ideal to make call assertions throughout the test case (e.g. that api calls are made correctly, args are correct, etc), much like how `:meck` exposes a few functions to make call assertions easier.

Are there plans for such an API? I can dig into this and raise a PR if so.

**Comment by edgurgel** [comment]
Would `verify!` do what you are describing https://hexdocs.pm/mimic/Mimic.html?#verify!/1 ?
