### ISSUE TITLE
Mimic doesn't work well with test coverage

### ISSUE THREAD

**Issue by kaorism** [edgurgel/mimic#6]
When I use Mimic with code coverage tool for ex `excoverall` or `coverex`

Mimic.copy  impact to coverage behavior that make coverage ignores and does not track modules which have been Mimic copied.

Please see Calculator module before and after calling `Mimic.copy(Coverage.Calculator)`

before:
<img width="773" alt="Screen Shot 2019-07-10 at 9 13 05 AM" src="https://user-images.githubusercontent.com/121340/60935157-2a2f3400-a2f3-11e9-9c78-8f0c45b887ec.png">

after:
<img width="850" alt="Screen Shot 2019-07-10 at 9 13 54 AM" src="https://user-images.githubusercontent.com/121340/60935191-416e2180-a2f3-11e9-86e9-073bea140e65.png">

https://github.com/kaorism/coverage-mimic

Thanks!

**Comment by edgurgel** [comment]
Amazing issue report! Thanks for submitting a repo reproducing the issue ❤️  . I will definitely check soon 👍

**Comment by kaorism** [comment]
thanks!

**Comment by edgurgel** [comment]
```
COV    FILE                                        LINES RELEVANT   MISSED
  0.0% lib/coverage.ex                                 9        0        0
100.0% lib/coverage/advanced_calculator.ex             7        1        0
 75.0% lib/coverage/application.ex                    29        4        1
100.0% lib/coverage/calculator.ex                      5        1        0
  0.0% lib/coverage_web.ex                            66        1        1
  0.0% lib/coverage_web/channels/user_socket.ex       33        0        0
  0.0% lib/coverage_web/endpoint.ex                   44        0        0
  0.0% lib/coverage_web/gettext.ex                    24        0        0
  0.0% lib/coverage_web/router.ex                     11        1        1
  0.0% lib/coverage_web/views/error_helpers.ex        33        3        3
100.0% lib/coverage_web/views/error_view.ex           16        1        0
  0.0% test/support/channel_case.ex                   31        1        1
100.0% test/support/conn_case.ex                      32        1        0
[TOTAL]  50.0%
````

This is the result now with the branch `cover`

**Comment by edgurgel** [comment]
I will probably release a new version tomorrow 🎉

**Comment by kaorism** [comment]
Great news! 🏆
