### ISSUE TITLE
Are there known issues with Mimic in combination with Phoenix PubSub?

### ISSUE THREAD

**Issue by mxgrn** [edgurgel/mimic#64]
I'm facing a problem of `expect` having no effect (that is, the function doesn't get stubbed) when the stubbed function is being called inside `handle_info` that processes a message from PubSub. Before I go into more details, does it ring a bell by any chance?

**Comment by edgurgel** [comment]
Do you see this issue if you force the mode to be global? See [here](https://github.com/edgurgel/mimic?tab=readme-ov-file#private-and-global-mode)

If that's the case you either need to run this specific set of tests as global or explicitly `allow` the pids of the processes that should see the mocked module.

**Comment by edgurgel** [comment]
Please feel free to reopen if the global mode does not fix the issue for you!
