### ISSUE TITLE
Intermittent Mimic.expect/4 test failure with Function not defined

### ISSUE THREAD

**Issue by axelclark** [edgurgel/mimic#66]
I have an intermittent test failure that looks similar to this:

```elixir
  1) test maybe_create_user/1 creates new user with api call to create_new_app_user/2 (MyApp.AccountsTest)
     test/my_app/accounts_test.exs:643
     ** (ArgumentError) Function create_new_app_user/2 not defined for MyApp.API
     code: |> Mimic.expect(:create_new_app_user, fn _, env ->
     stacktrace:
       (mimic 1.7.4) lib/mimic.ex:467: Mimic.raise_if_not_exported_function!/3
       (mimic 1.7.4) lib/mimic.ex:230: Mimic.expect/4
       test/my_app/accounts_test.exs:652: (test)
```

Looking at the Mimic source code [here](https://github.com/edgurgel/mimic/blob/9a096d7abf959669f8fd268c798eead726719488/lib/mimic.ex#L226-L235) and then [here](https://github.com/edgurgel/mimic/blob/9a096d7abf959669f8fd268c798eead726719488/lib/mimic.ex#L465-L469), it is calling [Kernal.function_exported?](https://hexdocs.pm/elixir/1.12/Kernel.html#function_exported?/3).

The docs on [Kernal.function_exported?](https://hexdocs.pm/elixir/1.12/Kernel.html#function_exported?/3) mention it can fail if the module is not loaded. That is the issue because the function does exist in the module. However, it only happens maybe 10% of the time.

I tried adding Application.ensure_all_started(:mimic) in the test_helper.exs, but that didn't fix the intermittently failing test.  

Then, I tried calling `Code.ensure_loaded(MyApp.API)` in the setup function in `AccountsTest`. That did seem to fix the problem.

I see `Mimic.copy/1` calls `Code.ensure_compiled/1`

https://github.com/edgurgel/mimic/blob/db733f5d6d1cfcceea06663eb3ee417a256973e8/lib/mimic.ex#L360

Does it make sense to add `Code.ensure_loaded/1` to `Mimic.raise_if_not_exported_function!/3`?  

https://github.com/edgurgel/mimic/blob/db733f5d6d1cfcceea06663eb3ee417a256973e8/lib/mimic.ex#L467-L471

Or is there some other approach that doesn't require me to add  `Code.ensure_loaded/1` to my setup function that I might be missing?

**Comment by edgurgel** [comment]
@axelclark first thanks for the very well detailed bug report!

I think changing to be Code.ensure_loaded is the way to go. Can you check if changing Mimic to do that works for you?

Would you mind sending a PR if it works?

**Comment by axelclark** [comment]
Sounds good!  I’ll try it out and submit a PR if it works

**Comment by brain-geek** [comment]
I've had this same issue and already made a fix PR: https://github.com/edgurgel/mimic/pull/72
