### ISSUE TITLE
A way to reset `expect`?

### ISSUE THREAD

**Issue by mxgrn** [edgurgel/mimic#76]
Hope it's ok to ask a question in the Issues.

Is there a way to drop an expectation that was set ealier?

My case for context: I call an `expect` in the setup block, but then for a specific test I want to override that, so it doesn't expect that call. I tried to cancel it with `reject` but it didn't work (and maybe it shouldn't after all).

**Comment by edgurgel** [comment]
First, totally fine to ask questions here :+1: 

No way to drop expectations. Supporting such feature would mean that the user would need to have some way to reference an expectation to then remove it and this would complicate quite a bit the codebase.

My suggestion would be to use [ExUnit setup blocks](https://hexdocs.pm/ex_unit/ExUnit.Callbacks.html#module-examples). One example that can be done per test is using module attribute `@tag` and specify which test you want the expectation to be set-up or not.

Something like this:

```elixir
defmodule ExampleTagModificationTest do
  use ExUnit.Case

  setup %{mimic: expect} do
    if expect do
       expect(MyModule, ....)
    end
    :ok
  end

  @tag mimic: true
  test "tags modify context" do
     # test here with expectation
  end
  
  @tag mimic: false
  test "tags modify context" do
     # test here without expectation
  end
end
```

**Comment by mxgrn** [comment]
That's a nice trick, with the tags ❤️ Another work-around that I ended up using so far was to actually split my tests into `describe` blocks that do and don't define the mock via the related `setup`.
