### ISSUE TITLE
BadMapError creating new Ash records

### ISSUE THREAD

**Issue by spacebat** [edgurgel/mimic#79]
I have been running Mimic 1.7.4 because upgrading led to a lot of BadMapErrors originating from [this line fetching the tenant of a new record](https://github.com/ash-project/ash/blob/v3.4.7/lib/ash/changeset/changeset.ex#L398). I have been printing the value of `record.__metadata__` in the `record` variable and found that occasionally it is `nil`, so that `Map.get(record, :__metadata__, %{})` gives `nil`, and I get a `BadMapError`.

Trying to debug something else related to Mimic (protocol undefined for nil of type Atom) I just tried upgrading to v1.10.0 but the BadMapErrors prevent using it. Each run of my test suite gives maybe a dozen such errors but which tests fail is random - seems like a race condition.

The call to `Ash.Changeset.new` normally works, `__metadata__` is `%{}` and the stack trace dumped just before getting the tenant is:
```elixir
 [
   {Process, :info, 2, [file: ~c"lib/process.ex", line: 864]},
   {Ash.Changeset, :new, 1,
    [file: ~c"lib/ash/changeset/changeset.ex", line: 395]},
   {Ash.Changeset, :for_create, 4,
    [file: ~c"lib/ash/changeset/changeset.ex", line: 1241]},
   {MyApp.MyModule, :create!, 2,
    [file: ~c"deps/ash/lib/ash/code_interface.ex", line: 682]},
   ...
 ]
```

Then when it fails, `__metadata__` is `nil` and the stack trace looks like:
```elixir 
 [
   {Process, :info, 2, [file: ~c"lib/process.ex", line: 864]},
   {Ash.Changeset, :new, 1,
    [file: ~c"lib/ash/changeset/changeset.ex", line: 395]},
   {Ash.Changeset, :for_create, 4,
    [file: ~c"lib/ash/changeset/changeset.ex", line: 1241]},
   {MyApp.MyModule.Mimic.Original.Module, :create!, 2,
    [file: ~c"deps/ash/lib/ash/code_interface.ex", line: 682]},
   ...
 ]
```

Perhaps it is a problem with Ash itself, but Mimic 1.7.4 doesn't exhibit this behaviour.

**Comment by spacebat** [comment]
I made a PR #80 that seems to fix this - though I don't know why it was intermittent.

**Comment by edgurgel** [comment]
Thanks @spacebat will check it out!

**Comment by edgurgel** [comment]
Mimic 1.10.1 has this bugfix! Thanks for hunting this down!
