### ISSUE TITLE
Mimic.Stub/2 Does Not Stub Calls When Used Inside GenServer

### ISSUE THREAD

**Issue by thduttonuk** [edgurgel/mimic#81]
I am encountering an issue with `Mimic.Stub/2` when using it inside a `GenServer` module. When I stub a function from `ServiceToStub` and call it from outside the `GenServer`, the stub works as expected. However, when the stubbed function is called from within a `GenServer` process, the original function implementation is invoked instead of the stubbed version.

Here is the code that demonstrates the issue:

```
Mimic.stub(ServiceToStub, :get_something, fn _ -> %{ "Data" => "" } end)
```

ServiceToStub Module:

```
defmodule ServiceToStub do
  def get_something(_) do
    %{}
  end
end

```

GenServer Module:

```
defmodule MyGenServer do
  use GenServer

  # Setup code...

  def generate() do
    GenServer.cast(__MODULE__, :run)
  end

  @impl true
  def handle_cast(:run, state) do
    %{} = ServiceToStub.get_something()
    {:noreply, state}
  end
end
```

Problem:
When `GenServer.generate()` is called, the `ServiceToStub.get_something()` call inside `handle_cast/2` runs the original implementation instead of the stubbed function.

Expected Behavior
The stubbed function should be called from within the `GenServer` process, returning `%{ "Data" => "" }` as defined in the stub.

Actual Behavior
The original `ServiceToStub.get_something/1` implementation is invoked, returning an empty map `%{}` instead of the stubbed response.

Additional Information
Elixir version: 1.17
Mimic version: 1.10.1

Steps to Reproduce
Define a module `ServiceToStub` with a function `get_something/1`.
Stub `ServiceToStub.get_something/1` using `Mimic.stub/2`.
Call `ServiceToStub.get_something/1` from outside a `GenServer` process to see the stub work correctly.
Call the same function from within a `GenServer` process using `GenServer.cast/2` and observe that the original function is executed.

Possible Solution
I suspect it might have something to do with how Mimic stubs work in a different process context within the `GenServer`. If anyone has encountered a similar issue or knows a workaround, your help would be greatly appreciated!

**Comment by edgurgel** [comment]
Hi @thduttonuk I think your issue is related to private vs  global mode and allowing specific pids. Have you read this bit of the README.md: https://github.com/edgurgel/mimic?tab=readme-ov-file#private-and-global-mode . The example shows a process spawned using spawn_link but it's the same idea for a GenServer.

**Comment by thduttonuk** [comment]
Thanks @edgurgel for the quick response, I should have read that part. I will close and test.
